---
- name: add puppet server dns names
  blockinfile:
      dest: '/etc/puppetlabs/puppet/puppet.conf'
      insertbefore: BOF
      block: |
        [main]
        dns_alt_names = {{ item }}
  loop:
    - "{{ puppet_server_dnsnames | list }}"

- name: enable autosign 
  lineinfile:
    dest: /etc/puppetlabs/puppet/puppet.conf
    regexp: autosign.*
    line: autosign = {{ autosign }}
