---
- name: add puppet server dns names
  blockinfile:
      dest: '/etc/puppetlabs/puppet/puppet.conf'
      insertbefore: BOF
      block: |
        [main]
        server = {{ puppet_server_dnsname }}
        dns_alt_names = puppet, {{ puppet_server_dnsname }}
  
- name: enable autosign 
  lineinfile:
    dest: /etc/puppetlabs/puppet/puppet.conf
    regexp: autosign.*
    line: autosign = {{ autosign }}

- name: certname on master 
  blockinfile:
      dest: '/etc/puppetlabs/puppet/puppet.conf'
      insertbefore: BOF
      block: |
        [master]
        certname = {{ puppet_server_dnsname }}
